"""empty message

Revision ID: 403e33bdc08e
Revises: 
Create Date: 2021-08-03 18:38:45.616672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '403e33bdc08e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor', sa.Column('start_duty_time', sa.Time(), nullable=True))
    op.add_column('vendor', sa.Column('end_duty_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor', 'end_duty_time')
    op.drop_column('vendor', 'start_duty_time')
    # ### end Alembic commands ###
